chanzuckerberg/redis-memo

- lib/redis_memo/memoize_method.rb
- lib/redis_memo/memoize_records/cached_select.rb
This allows users to pass in a method_id proc to define custom method_id.
We use custom method_id to trace cached SQL queries:
- now there will be a cache_hit tag directly attached to each query
- all the resources have the same operation name (cache.read or cache.write) so it's easier to view
- even harder to have a hash collision, each SHA1 hash is now prefixed with unparameterized SQL queries
- ci
> Replace trace span memoize_query with cache.read/write

- lib/redis_memo/memoize_query.rb
- lib/redis_memo/memoize_query/cached_select.rb
This adds an env var so we can turn off any SQL query caching per table.
Note: The current behavior needs to be updated once we allow memoized methods to set dependencies on Arel: when we disable query caching, the method memorization should probably not be affected.
- ci
1. https://github.com/chanzuckerberg/redis-memo/pull/7 [bug fix] Reject unbound select queries
2. https://github.com/chanzuckerberg/redis-memo/pull/5 👉 **Add env var: Turn off query caching per table** 👈 (You are here)
3. https://github.com/chanzuckerberg/redis-memo/pull/6 Drop support for JOIN queries
> [feature] Add an env var to turn off query caching per table

- lib/redis_memo/memoize_query/cached_select.rb
- spec/memoize_query_spec.rb
We don't really support JOINs well. Currently, it's still possible to have stale cache results if we are selecting from joined tables that do not filter conditions.
This drops the support for JON queries and we can revisit this later.
- ci
1. https://github.com/chanzuckerberg/redis-memo/pull/6 👉 **Drop support for JOIN queries** 👈 (You are here)
> [bug fix] Drop support for JOIN queries

- lib/redis_memo/memoizable/dependency.rb
Follow up to [this](https://github.com/chanzuckerberg/redis-memo/pull/8#discussion_r568248106) comment, use a static class that responds to === method instead of a runtime proc.
rspecs pass
> [fix] Define static class with === method to avoid using runtime proc in case statement

- lib/redis_memo/memoize_query/invalidation.rb
We invalidate all cached results when doing an `import`, yet there's another method provided by [activerecord-import](https://github.com/zdennis/activerecord-import): `import!` this PR also adds invalidation for that method.
- ci
> [bug fix] Invalidate cache on import!

- lib/redis_memo/memoize_method.rb
- spec/memoizable/dependency_spec.rb
From [here](https://github.com/chanzuckerberg/redis-memo/blob/main/lib/redis_memo/memoize_method.rb#L82), the object reference is used to call the dependency block, not the class. Fix extracting dependencies when calling `dependency_of` to use the object reference as well.
Usually we have something like
```
memoize_method :method |_, *args| do...
end
```
so we don't care about the first argument.
Added specs to cover scenario. Without this change, the specs fail with something like
```
Failure/Error: depends_on RedisMemo::Memoizable.new(id: obj.id, val: x)
NoMethodError:
undefined method `id' for #<Class:0x000056241936d420>
```
Specs succeed with this change
> [fix] Extract dependencies from object reference instead of class

- lib/redis_memo/memoize_query.rb
- spec/memoize_query_spec.rb
This adds support for Rails Single-Table Inheritance (STI). When memoizing queries on a table that has STI, we should only call `memoize_table_column` on the root model.
The current code almost completely supports STI already -- we only need to change the logic create_memo so that it uses the table name as meta data instead of the name of the model class.
- ci
> [feature] Support Rails Single-Table Inheritance

- lib/redis_memo.rb
- lib/redis_memo/memoizable.rb
- lib/redis_memo/memoizable/invalidation.rb
In spec, or some other use cases, people might want to overwrite the existing UUID generation behavior in RedisMemo. This PR adds a common entry point for the UUID generation for people to overwrite.
- ci
> [feature] Support overwriting uuid generation

- lib/redis_memo/cache.rb
- lib/redis_memo/memoize_method.rb
- spec/memoizable/dependency_spec.rb
A follow up to [this](https://github.com/chanzuckerberg/redis-memo/pull/8#discussion_r568833999) comment, add a request level cache for caching the recursive computation to extract dependencies.
Added specs for the new scenario
> [feature] Locally cache computation to extract dependencies

- lib/redis_memo/memoizable/dependency.rb
- lib/redis_memo/memoize_query/cached_select.rb
- spec/memoizable/dependency_spec.rb
Enable using an ActiveRecord::Relation object as a dependency of a memoized method. Do this by:
- Adding a new case for `ActiveRecord::Relation` while extracting dependencies in `RedisMemo::Dependency.depends_on`
- Re-use the logic to extract bind params while executing a query. (Is it safe to also hijack the thread local variables that are shared between activerecord/redismemo in this case?)
Follow up:
- Do we want to be able to specify queries from finder methods? e.g. `.find(), .pluck()`, which immediately execute the query instead of lazy loading it like ActiveRecord::Relation?
Added specs
> [feature] Allow using an ActiveRecord::Relation as a dependency

- lib/redis_memo/memoize_query.rb
- lib/redis_memo/memoize_query/invalidation.rb
- redis-memo.gemspec
- spec/memoize_query_spec.rb
When using PostgreSQL, we can reduce the number of records we have to invalidate for each import.
Postgres supports "RETURNING id", so we can easily get the result set back and perform invalidation on the created result set.
We also need to send another query before the import in case it's an UPSERT operation. In this case, we'd need to query all the values before updating so we can properly invalidate the cache.
As a result, we are now sending two extra SELECT SQL queries for each import operation. This should not be an issue since it only makes the import slightly slower -- the result set of both queries is strongly correlated with the size of the records to import (cannot be too big).
- added test cases
- ci
> [feature] Optimize activerecord-import cache invalidation

- lib/redis_memo/after_commit.rb
- lib/redis_memo/memoizable/invalidation.rb
- lib/redis_memo/tracer.rb
- spec/memoizable/invalidation_spec.rb
This adds more visibility to:
- how long each invalidation request has spent in the invalidation queue
- we can see the operation history given a memoizable (hashed). To debug, we first need to generate the same key on the client-side. We do this to avoid sending PII to 3rd party tracing service such as datadog
- this has been covered by test cases
- ci
> [feature] Trace invalidation key and enqueue_to_finish duration

- lib/redis_memo/cache.rb
- lib/redis_memo/memoizable.rb
- lib/redis_memo/memoizable/invalidation.rb
- spec/cache_spec.rb
In Rails 6, we'd need to pass in a `raw: true` for the RedisCacheStore to properly deserialize the raw version values we set.
- ci
- tested locally with Rails 6
> [rails 6] Explictly set raw option when reading versions

- .travis.yml
The docker service is not really being used right now, and it's causing some build flakiness.
- ci
> [ci] Remove docker service

- redis-memo.gemspec
With this PR, we will start to use activerecord 6 for ci testing.
In the following PRs, I will configure the CI to test with multiple activerecord versions.
- ci
> [rails 6] Update dependent gem versions

- lib/redis_memo.rb
- lib/redis_memo/future.rb
- lib/redis_memo/memoizable/dependency.rb
- lib/redis_memo/memoize_method.rb
- spec/memoizable/dependency_spec.rb
Support the following use case to allow clients to raise an error `RedisMemo::WithoutMemoization` if they don't want to memoize a method based on certain method args.
```
def method(without_memoization: false)
end
memoize_method :method do |_, without_memoization|
raise RedisMemo::WithoutMemoization if without_memoization
depends_on ....
end
end
``` 
- Change the behavior so that instead of throwing an error when an Arel dependency isn't memoized, fall back to calling the original method without memoization.
- Also refactor a bit so that we extract dependencies before creating the future.
Existing specs pass, also added a few specs to test this behavior.
> [feature] Support memoizing a method conditionally

- lib/redis_memo/memoize_query.rb
- lib/redis_memo/memoize_query/invalidation.rb
- lib/redis_memo/options.rb
- spec/memoize_query_spec.rb
This adds a limit to the number of records we would select from the database. Previously I thought we're selecting by uniq_by columns -- I was confused and wrong. We're actually selecting by the columns_to_update so the number of records can be super big.
This PR:
- Sets such limit. If we're going to load many records; simply invalidate everything
- We only care about the columns_to_update if they overlap with the columns we're memorizing
- Adds monitoring
- ci
> [feature] Add bulk_operations invalidation limit

- lib/redis_memo/cache.rb
- lib/redis_memo/connection_pool.rb
- lib/redis_memo/memoizable/invalidation.rb
- lib/redis_memo/options.rb
- redis-memo.gemspec
- spec/connection_pool_spec.rb
With https://github.com/mperham/connection_pool, each time the block is called, it is supposed to create a new client object.
> [fix] Create new clients for connection_pool

- lib/redis_memo/memoize_query.rb
In case something went wrong, we could use an env var to skip caching without any code changes.
> [feature] Add an env var to skip memoize_table_column

- lib/redis_memo/redis.rb
Since we're calling `shift` on the options, the default options are altered whenever we create a new Redis client.
This fixes the issue.
> [fix] Avoid mutating default options when building Redis client

- lib/redis_memo/memoizable/dependency.rb
- lib/redis_memo/memoize_query/cached_select.rb
This marks `depends_on Model, **attrs` as a private API. Users can no longer set dependencies on some queries without calling `extract_bind_params`.
- ci
> [change] Drop support for depends_on ActiveRecord model

- lib/redis_memo/memoize_query/invalidation.rb
- lib/redis_memo/options.rb
- spec/memoize_query_spec.rb
This changes the upsert invalidation to use `select_by_conflict_target`. By selecting by the conflict target, we will be strictly selecting fewer records than columns_to_update, since the number of rows that satisfy the conflict target is less or equal to the number of records we're importing.
- added test cases
- ci
> [feature] Optimize invalidation for bulk_upsert

- lib/redis_memo/memoize_method.rb
- lib/redis_memo/memoize_query/cached_select.rb
- spec/memoizable/dependency_spec.rb
1. For the local dependency cache, use the class object instead of the instance as a key. The dependency block's first argument is always the instance anyway, so extracted dependencies can be shared at the class level.
2. Only look at method arguments which the dependency block cares about in order to define dependent memos, following the convention that `:_` means we don't care about the argument. This helps us locally cache extracting dependencies from an Arel query without having to further call different connection methods to get values (e.g. prepare, name).
Added a spec for the new scenario.
> [feature] Optimize the local dependency cache based on dependency block args

- lib/redis_memo/memoize_query/invalidation.rb
- spec/memoize_query_spec.rb
When importing an empty array, conflict_target_relation could be nil and could not be loaded.
- added a test case
- ci
> [fix] Handle nil conflict_target_relation

- redis-memo.gemspec
- Handle nil conflict_target_relation (#49) . This is needed to bump the version in traject.
> Release v0.1.1

- lib/redis_memo/memoize_query/cached_select.rb
- spec/memoize_query_spec.rb
https://app.clubhouse.io/czi-edu/story/65265/redis-memo-sql-ast-support-order-by
order by query should be supported since `node.orders` is not considered when parsing `node.cores`, and whatever in the `node.orders` should not be considered as a dependency. Made the change by removing the restriction on order_by and added test cases for bounded and unbounded order by queries.
Open to suggestion as this is my first time committing to this repo, and thanks @donaldong so much for the help!!
> [feature] Support Arel queries with order by

- lib/redis_memo/testing.rb
- spec/spec_helper.rb
- spec/testing_spec.rb
We've seen flaky specs for code which uses redis-memo in traject. One hypothesis is that Redis transient connection errors are causing cache invalidation to not work each time.
This PR allows overriding the default behavior of redis-memo so that invaildation is more robust. If the invalidation queue is not. empty before callilng a memoized method, fall back to `RedisMemo.without_memo`
This is loosely based on how [sidekiq](https://github.com/mperham/sidekiq/blob/f0ddebc7406fe4b78333fbc5f14488a38b9ccebc/lib/sidekiq/testing.rb) has different testing modes and overrides default behavior.
Wrote some specs to test the behavior of the class.
> [feature][testing] Override default redis-memo behavior for more robust testing

- lib/redis_memo/memoizable/dependency.rb
- spec/memoizable/dependency_spec.rb
If the kill switch is on to disable all cached select queries on redis-memo, then memoize_method is never called for `connection.exec_query`, and therefore :dependency_of is never dynamically defined. This falls back to the uncached method in case `:dependency_of` is not defined.
> [fix] Fall back to uncached flow while extracting arel dependencies if active record queries are disabled

- lib/redis_memo.rb
- lib/redis_memo/cache.rb
- lib/redis_memo/middleware.rb
- spec/cache_spec.rb
- If there's an issue with the Redis server and a request makes multiple calls to the RedisMemo cache, it'll just keep timing out and failing to connect. This can cause a request which makes multiple cache calls to be really slow.
- To mitigate this issue, keep track of the connection attempts and max connection attempts in a thread local variable. If we reach the max connection attempts, fall back to `RedisMemo.without_memo` for the rest of the request.
- Wrote specs for new feature
- Still testing a bit manually, but I ran traject locally and pointed to this branch, and can confirm that when redis raises connection errors, it only attempts to connect n times.
> [feature] Add max connection attempts to RedisMemo middleware

- lib/redis_memo.rb
- lib/redis_memo/memoize_query.rb
Add a global kill switch for redis-memo. This should turn off all calls to the redis cache, as well as installing the auto-invalidation classes for memoized table columns on ActiveRecord.
Tested manually on traject that this works.
> [feature] Add redis memo env variable for global kill switch

- lib/redis_memo/memoizable/invalidation.rb
I think it'd be helpful to use the error handler/log errors on invalidation. We still haven't figured out why rspecs are sometimes flaky with redis-memo - while we see cache out of date errors, we don't see any invalidation errors.
> Log errors and call error handler on invalidation

- lib/redis_memo/memoize_query/cached_select.rb
- spec/memoize_query_spec.rb
This PR enables queries with that has both NOT and other bound queries. 
Previously we decided to not to cache any queries with NOT, however, queries with both NOT and other bound queries can be cached. E.g
```
Site.where(a: 1).where.not(b: 1) can be cached based on a as dependency 
Site.where.not(b: 1) should not be cached
```
My current approach is to return `bind_params` when we parse a `notequal` statement, so that 
- for queries with only NOT, we return an empty object 
- for queries with NOT and other bound conditions, it will involve those conditions and cache
rspec
> [feature] enable caching on queries with NOT

- lib/redis_memo/cache.rb
- spec/cache_spec.rb
redis_cache_store only rescues `Redis::BaseErrors`. We should also rescue `ConnectionPool::TimeoutErrors` thrown from the connection_pool gem, since these are transient and shouldn't fail the request if the cache read/write fails.
Overwrite the private method failsafe defined in [redis_cache_store](https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/activesupport/lib/active_support/cache/redis_cache_store.rb#L477) to also catch ConnectionPool::TimeoutErrors.
- Wrote additional specs
- I think the build currently on main is failing, unrelated to this change
> [bug fix] Rescue ConnectionPool::TimeoutError

- lib/redis_memo/memoize_query/cached_select.rb
- spec/memoize_query_spec.rb
This PR is to support the queries that have range in it. such as '>=', '<=', etc., and also combine the `NotEqual` query we had in #62 since they can all be merged into the `NodeHasComparator` condition in this PR.
Regarding the rspec, I created several shared examples so we can test multiple similar behaviors. 
Previously we decided to not to cache any queries with these comparison operators, however, queries with both comparison operators and other bound queries can be cached. E.g
```
Site.where(a: 1).where('b > ?' 1) can be cached based on a as dependency 
Site.where('b > ?' 1) should not be cached
```
Also, as according to [here](https://piechowski.io/post/how-to-use-greater-than-less-than-active-record/), there are two forms of queries with comparator: 
1. Site.where(a: 1).where('b > …
> [feature] support more queries with range (>=, <= etc)

- lib/redis_memo.rb
- lib/redis_memo/memoize_query.rb
- lib/redis_memo/railtie.rb
- redis-memo.gemspec
- spec/railtie_spec.rb
- spec/spec_helper.rb
This uses railties to load RedisMemo::Middleware. The implementation is identical to https://github.com/steveklabnik/request_store/blob/master/lib/request_store/railtie.rb.
If a project has both RedisMemo and RequestStore configured, RedisMemo and RequestStore middleware will be next to each other. Their relative ordering does not matter much.
- added a test case to describe this behavior
- ci
> [feature] Use railtie to load middleware

- lib/redis_memo.rb
- lib/redis_memo/batch.rb
- lib/redis_memo/cache.rb
- lib/redis_memo/memoize_query/cached_select.rb
- lib/redis_memo/thread_local_var.rb
- spec/thread_local_var_spec.rb
This is an attempt to dry up the thread-local vars. Currently, the key is defined manually and might have collisions.
> [refactor] Define ThreadLocalVar

- lib/redis_memo.rb
- lib/redis_memo/memoize_query.rb
- lib/redis_memo/middleware.rb
- lib/redis_memo/options.rb
- spec/options_spec.rb
Merge redis-memo specific env vars into the DefaultOptions class. See comment in https://github.com/chanzuckerberg/redis-memo/pull/58#discussion_r594725937
This feels like somewhat of a breaking change; when we merge this into Traject, we need to make sure to set the option values accordingly with the correct types.
- Added specs for options to `disable_all`, and `disable_table`.
- I didn't add a test for the option `disable_cached_select`; this option installs the cached_select logic onto the connection class directly. I couldn't find a good way to force reload the connection class definition, or undo the redis-memo changes on this class, without breaking other stuff.
> [cleanup] Move redis-memo specific environment variables into DefaultOptions

- .travis.yml
- gemfiles/5.2.gemfile
- gemfiles/6.0.gemfile
- gemfiles/6.1.gemfile
- lib/redis_memo.rb
- lib/redis_memo/memoize_method.rb
- lib/redis_memo/memoize_query/cached_select/connection_adapter.rb
- lib/redis_memo/memoize_query/invalidation.rb
- redis-memo.gemspec
- spec/memoizable/dependency_spec.rb
This adds Ruby 3 support. ~Since there's a Ruby bug https://bugs.ruby-lang.org/issues/10856 in Ruby versions prior to 2.7, I'm dropping support to those versions instead of trying to deal with the bug at runtime.~
~Learn more [here](https://summitlearning2.slack.com/archives/CS8V0ERCK/p1617658626015000)~
Updated to use `ruby2_keywords`
- ci
> [feature] Support Ruby 3.x

- lib/redis_memo/connection_pool.rb
- lib/redis_memo/memoizable/bump_version.lua
- lib/redis_memo/memoizable/invalidation.rb
- lib/redis_memo/redis.rb
- spec/after_commit_spec.rb
- spec/memoizable/invalidation_spec.rb
- spec/redis_spec.rb
- Move Lua code to a separate fille and run evalsha after a script is already loaded instead of eval
Wrote additional specs to confirm behavior
> [feature] Move lua to a separate file, run evalsha after script is already loaded

- lib/redis_memo/memoize_query/cached_select.rb
Adding rdoc for cache select.  This is what I thought was useful when developing the features of #63, as it helps to understand the logic of parsing bind params, though this is not a file that will be used much by the users.
> [doc] rdoc for cache select

- docs/examples/config.rb
- docs/wiki/Configure-RedisMemo.md
- lib/redis_memo/options.rb
This adds an example configuration, modified from the ones we have in traject, as a reference.
> [doc] Check in an example config

- README.md
Just noticed we didn't say anything about the min Redis version in the README file. This adds it.
We can also check the min Redis version in runtime (raise an error if the Redis version is too old) but that might be an overkill assuming users would read the README page first. (and might be too strict, since it's still fine on old Redis versions if it does not run out of memory)
> [doc] Specify min Redis version 6.0.0

- lib/redis_memo/memoizable/dependency.rb
- lib/redis_memo/memoize_query/cached_select.rb
- lib/redis_memo/memoize_query/cached_select/bind_params.rb
- lib/redis_memo/options.rb
- lib/redis_memo/util.rb
- spec/memoize_query/cached_select/bind_params_spec.rb
This adds a feature to respect `max_query_dependency_size`.
Users might have big queries with a super big dependency list -- if we perform cross-product on those dependencies, it might create millions of entries. Thus, this adds a way to "plan" first, before actually extracting the bind_params.
This also adds a tracer span, so we can see the time spent in extracting dependies.
- Added test cases
> [feature] Support max_query_dependency_size

- lib/redis_memo/memoize_query/cached_select/connection_adapter.rb
- lib/redis_memo/redis.rb
Currently, we're printing way too many debug logs. Those logs are hardly useful to anyone unless they're developing redis-memo.
We can simply remove those Redis logs and display an overall query latency. Note the latency is an over-estmation. It includes more than just the time spent on the redis round trips
> [change] Reduce logs volume
