- lib/redis_memo/memoize_query.rb
- lib/redis_memo/memoize_query/cached_select.rb
- spec/memoize_query_spec.rb
`teacher.sites`
```SQL
SELECT "sites".* FROM "sites" INNER JOIN "teacher_sites" ON "sites"."id" = "teacher_sites"."site_id" WHERE "teacher_sites"."teacher_id" = $1
```
This query should not be memoized as changing individual site records would not cause any invalidations
This query is memoized
Make sure the table we're selecting from has some filtering conditions before memorizing it
- added test cases
- ci
> [bug fix] Reject unbound select queries

- redis-memo.gemspec
- #7 Drop support for JOIN queries
- #5 Env var to turn off query caching per table
> Release v0.0.0.beta.1

- redis-memo.gemspec
- #8 Pull in dependencies defined by other methods
- #11 Support Rails Single-Table Inheritance
- #10 Invalidate cache on import!
- #13 Extract dependencies from object reference instead of class
> Release v0.0.0.beta.2

- lib/redis-memo.rb
- lib/redis_memo.rb
> [doc] Add yard doc for the top-level namespace

- redis-memo.gemspec
- #14 Locally cache computation to extract dependencies
- #16 Support overwriting uuid generation
- #18 Allow using an ActiveRecord::Relation as a dependency
- #19 Optimize activerecord-import cache invalidation
- #20 Trace invalidation key and enqueue_to_finish duration
> Release v0.0.0.beta.3

- lib/redis_memo/memoize_query/cached_select.rb
This adds support for the updated activerecord API in version >= 6. The we support we're adding here is backward compatible to early activerecord versions (>= 5).
- ci
> [rails 6] Handle updated activerecord API

- lib/redis_memo/cache.rb
- lib/redis_memo/connection_pool.rb
- lib/redis_memo/options.rb
- redis-memo.gemspec
- spec/connection_pool_spec.rb
This adds a connection_pool to allow us to offload async write requests (including bumping versions) faster.
- added test cases 
- ci
> [feature] Add Redis connection pool

- README.md
Please edit / comment directly on https://docs.google.com/document/d/1TL5Rq9CZTDjQNUnknbCZGJsKn7teuWPozXL4w3g_ITE
> [doc] Add README.md

- redis-memo.gemspec
- Support Rails 6 versions
- Support memoizing a method conditionally (#28)
- Add Redis connection pool (#29)
- Add bulk_operations invalidation limit (#31)
- Add an env var to skip memoize_table_column (#30)
- Avoid fetching too many records for bulk_operations invalidation (#31)
> Release v0.0.0.beta.4

- redis-memo.gemspec
- [fix] Avoid mutating default options when building Redis client (#35)
> Release v0.0.0.beta.5

- lib/redis_memo/memoize_query/invalidation.rb
- spec/memoize_query_spec.rb
An error caught by unit tests in traject.
- add a test case
- ci
> [fix] Import records could be empty

- redis-memo.gemspec
- Import records could be empty (#38)
> Release v0.0.0.beta.6

- README.md
Add references to
https://github.com/chanzuckerberg/redis-memo/wiki/Version-Addressable
> [doc] Version Addressable

- lib/redis_memo/memoize_query/invalidation.rb
- spec/memoize_query_spec.rb
When inserting new records, we can first check the current max id. After performing the insert, we can query records with ids greater than the value we saved before and invalidate them.
This PR also allows us to improve invalidation in import.
- added test cases to cover the added code paths
- ci
> [feature] Optimize invalidation for bulk_insert

- redis-memo.gemspec
- Optimize invalidation for bulk_insert (#45)
- Optimize invalidation for bulk_upsert (#46)
- Optimize local dependency cache based on dependency block args (#40)
- Drop support for dependency on ActiveRecord model (#43)
- Version addressable caching system (#37)
- Caching without changing call sites (#42)
- Hierarchical caching (#44)
> Release v0.1.0

- redis-memo.gemspec
- Override default redis-memo behavior for more robust invalidation (#51)
- Support order_by queries (#52)
> Release v0.1.2

- README.md
https://github.com/chanzuckerberg/redis-memo/wiki/Auto-Invalidation-with-ActiveRecord
> [doc] Auto Invalidation with ActiveRecord

- README.md
https://github.com/chanzuckerberg/redis-memo/wiki/Ensure-consistency-during-deployments
> [doc] Ensure consistency during deployments

- README.md
https://github.com/chanzuckerberg/redis-memo/wiki/Multi-Version-Concurrency-Control
> [doc] Multi Version Concurrency Control

- redis-memo.gemspec
- Add max connection attempts to RedisMemo middleware (#58)
- Add redis memo env var for global kill switch (#59)
- Log errors and call error handler on invalidation (#60)
- Fall back to uncached flow while extracting arel dependencies if active record queries are disabled (#54)
- Auto invalidation with ActiveRecord (#55)
- Ensure consistency during deployements (#56)
- Multi Version Concurrency Control (#57)
> Release v0.1.3

- redis-memo.gemspec
- Enable caching queries with NOT conditions (#62)
- Rescue ConnectionPool::TimeoutError (#64)
> Release v0.1.4

- lib/redis_memo.rb
- lib/redis_memo/memoizable.rb
- lib/redis_memo/memoizable/invalidation.rb
- lib/redis_memo/memoize_method.rb
- lib/redis_memo/util.rb
This moves code around. No functionality changes.
> [refactor] Add RedisMemo::Util

- lib/redis_memo.rb
- lib/redis_memo/errors.rb
This moves some code around. No functionality changes.
> [refactor] Move errors to a separate file

- README.md
- lib/redis_memo/options.rb
- Added a link in the readme to the configuration wiki page. I also modified this page quite a bit - feel free to edit https://github.com/chanzuckerberg/redis-memo/wiki/Configure-RedisMemo
- Added rdoc comments in options class
> [doc] Add options doc

- .rubocop/config.yml
- .rubocop/lint.yml
- .rubocop/naming.yml
- .rubocop/rspec.yml
- .rubocop/style.yml
- .travis.yml
- lib/redis_memo.rb
- lib/redis_memo/batch.rb
- lib/redis_memo/cache.rb
- lib/redis_memo/connection_pool.rb
- lib/redis_memo/future.rb
- lib/redis_memo/memoizable/dependency.rb
- lib/redis_memo/memoizable/invalidation.rb
- lib/redis_memo/memoize_method.rb
- lib/redis_memo/memoize_query.rb
- lib/redis_memo/memoize_query/cached_select.rb
- lib/redis_memo/memoize_query/invalidation.rb
- lib/redis_memo/options.rb
- lib/redis_memo/redis.rb
- spec/memoizable/dependency_spec.rb
- spec/memoizable/invalidation_spec.rb
- spec/memoize_query_spec.rb
- spec/options_spec.rb
- spec/railtie_spec.rb
- spec/redis_spec.rb
This fixes/disables lint errors we have and enables running rubocop for each build.
- ci
> [CI] Run rubocop for each build

- lib/redis_memo.rb
- lib/redis_memo/batch.rb
- lib/redis_memo/future.rb
- lib/redis_memo/memoize_method.rb
- spec/memoize_method_spec.rb
Added a few more rdocs for batch and memoize_method. Feel free to edit or suggest edits as needed!
> Add more rdocs for RedisMemo::Batch and RedisMemo::MemoizeMethod

- lib/redis_memo/memoizable.rb
- lib/redis_memo/memoizable/invalidation.rb
- lib/redis_memo/memoize_method.rb
- spec/after_commit_spec.rb
- spec/memoizable/invalidation_spec.rb
- spec/memoizable_spec.rb
Rdocs for the RedisMemo::Memoizable and RedisMemo::Memoizable::Invalidation classes
- rubocop and specs pass after using `.send(..` on methods that are made private
> [doc] Add docs for RedisMemo::Memoizable and RedisMemo::Memoizable::Invalidation

- lib/redis_memo.rb
- lib/redis_memo/future.rb
- lib/redis_memo/memoize_method.rb
- lib/redis_memo/memoize_query/cached_select/connection_adapter.rb
- lib/redis_memo/memoize_query/invalidation.rb
- lib/redis_memo/testing.rb
- spec/memoize_method_spec.rb
- spec/memoize_query_spec.rb
- Rename without_memo -> without_memoization
- Mostly just a find and replace :) 
Specs pass
> Rename without_memo -> without_memoization

- lib/redis_memo/middleware.rb
- spec/railtie_spec.rb
This error is caught by traject ci.
- added a test case to cover this code path
> [fix] undefined method max_connection_attempts

- redis-memo.gemspec
- Inline cache validation sample percentage (#78): `config.cache_validation_sampler` is replaced with `config.cache_validation_sample_percentage`
- Rename `RedisMemo.without_memo` -> `RedisMemo.without_memoization` (#85)
- Support more queries with range (>=, <= etc) (#63)
- Use railtie to load middleware (#69)
- Support Ruby 3.x (#83)
- Move lua to a separate file, run evalsha after script is already loaded (#84)
- Update README (#73)
- Add options doc (#77)
- Add more rdocs for RedisMemo::Batch and RedisMemo::MemoizeMethod (#80)
- Add rdocs for RedisMemo::MemoizeQuery (#81)
- Add docs for RedisMemo::Memoizable and RedisMemo::Memoizable::Invalidation (#82)
- Add rdocs for cache select (#91)
- Check in wiki pages (#86)
- Check in an example config (#89)
- Fix rubocop lint errors (#79)
- …
> Release v1.0.0

- redis-memo.gemspec
- Support max_query_dependency_size (#94)
- Reduce debug logs volume (#95)
> Release v1.1.0
